makecode:
  target: arcade
  platform: arcade
  home_url: https://arcade.makecode.com/
remote-theme: jekyll-dash
include:
  - assets
  - README.md
plugins:
  - jekyll-remote-theme
show_downloads: false