name: MakeCode

on:
  push:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}          
      - name: Cache npm and makecode
        uses: actions/cache@v2
        with:
            path: |
                ~/.npm
                ~/.pxt/mkc-cache
            key: ${{ runner.os }}-${{ hashFiles('pxt.json') }}-${{ hashFiles('mkc*json') }}
            restore-keys: |
                ${{ runner.os }}-
      - name: npm install makecode
        run: |
            npm install -g makecode
      - name: build js
        run: |
          makecode --java-script
      - name: build hardware F4,D5,N4,N3
        run: |
          makecode --hw F4,D5,N4,N3
      - name: build github pages
        run: |
          cp ./built/binary.js ./assets/js/binary.js
      - name: upload github pages 
        uses: stefanzweifel/git-auto-commit-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_pattern: ./assets/*          
      - name: upload bundled firmware
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./built/combined.uf2
          asset_name: arcade.uf2
          asset_content_type: application/octet-stream
